name: BUILD AND PUBLISH SITUATIONROOM.CORE.BACKEND DOCKER IMAGE

on:
  push:
    branches: ["master"]
    paths:
      - "src/backend/**"
  pull_request:
    branches: ["master"]
    paths:
      - "src/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          DATE=$(date +%Y-%m-%d)
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/situationroom-backend

          # Build
          docker build src/backend/Hermes.SituationRoom.Web \
            --file src/backend/Hermes.SituationRoom.Web/Dockerfile \
            --tag $IMAGE_NAME:${DATE}.${GITHUB_RUN_NUMBER} \
            --tag $IMAGE_NAME:latest

          # Push
          docker push $IMAGE_NAME:${DATE}.${GITHUB_RUN_NUMBER}
          docker push $IMAGE_NAME:latest
